# apps/rook-ceph-resources/pool.yaml

# 1. 블록 스토리지 풀
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
# 2. 파일 시스템 (메타데이터 풀과 데이터 풀 포함)
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: replicated
      replicated:
        size: 3
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 0
    activeStandby: true
  # 3. Ceph Object Store (RGW) 정의
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph
spec:
  # RGW(Rados Gateway)가 데이터를 저장할 풀들에 대한 설정입니다.
  metadataPool:
    failureDomain: host
    replicated:
      size: 3 # 메타데이터는 3중 복제로 안전하게 보관합니다.
  dataPool:
    failureDomain: host
    replicated:
      size: 3 # 실제 데이터도 3중 복제로 안전하게 보관합니다.

  # RGW 데몬(S3 API 요청을 처리하는 서버)을 몇 개 띄울지 결정합니다.
  # 고가용성을 위해 최소 2개 이상을 권장합니다.
  gateway:
    replicas: 2
    # RGW 서비스가 외부에서 접근할 수 있도록 ClusterIP 타입의 서비스를 생성합니다.
    # 포트는 기본적으로 80을 사용합니다.
    port: 80
    # RGW Pod가 사용할 리소스 요청/제한
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
