apiVersion: v1
kind: Pod
metadata:
  name: test-s3-client
  namespace: accumulation # accumulation 네임스페이스에 생성
spec:
  containers:
  - name: mc
    image: minio/mc
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
      - name: S3_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: iceberg-bucket-claim # 2단계에서 확인한 Secret 이름
            key: AWS_ACCESS_KEY_ID
      - name: S3_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: iceberg-bucket-claim # 2단계에서 확인한 Secret 이름
            key: AWS_SECRET_ACCESS_KEY
      - name: S3_HOST
        valueFrom:
          configMapKeyRef:
            name: iceberg-bucket-claim # 2단계에서 확인한 ConfigMap 이름
            key: BUCKET_HOST
      - name: S3_PORT
        valueFrom:
          configMapKeyRef:
            name: iceberg-bucket-claim # 2단계에서 확인한 ConfigMap 이름
            key: BUCKET_PORT
