# Kafka 브로커에 외부에서 접속하기 위한 LoadBalancer 타입의 서비스를 생성합니다.
apiVersion: v1
kind: Service
metadata:
  name: kafka-external-lb
  namespace: confluent
spec:
  type: LoadBalancer
  # 이 selector는 Confluent Operator가 생성하는 Kafka Pod들의 라벨과 일치합니다.
  selector:
    app: kafka
    # platform.confluent.io/component: kafka-broker
  ports:
    - name: external-kafka
      port: 9092
      targetPort: 9092 # Kafka Pod의 외부 접속용 포트 (기본값)
