apiVersion: platform.confluent.io/v1beta1
kind: KafkaConnector
metadata:
  name: s3-sink-parking-events
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
  connectClusterRef:
    name: connect
  maxTasks: 2
  configs:
    connector.class: "io.confluent.connect.s3.S3SinkConnector"
    topics: "parking-entries,parking-exits"
    # ★★★★★ [핵심 수정] Parquet 대신 JsonFormat을 사용합니다. ★★★★★
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    flush.size: "100"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    s3.bucket.name: "iceberg"
    store.url: "http://rook-ceph-rgw-my-store.rook-ceph.svc:80"
    topics.dir: "landing"
    partitioner.class: "io.confluent.connect.storage.partitioner.TimeBasedPartitioner"
    path.format: "'year'=YYYY/'month'=MM/'day'=dd"
    partition.duration.ms: "86400000"
    locale: "ko_KR"
    timezone: "Asia/Seoul"
    timestamp.extractor: "Record"
  secretRef:
    name: s3-credentials
