# 파일: confluent-resources/s3-sink-connector.yaml
apiVersion: platform.confluent.io/v1beta1
kind: KafkaConnector
metadata:
  name: s3-sink-parking-events
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
  connectClusterRef:
    name: connect
  maxTasks: 2
  configs:
    "connector.class": "io.confluent.connect.s3.S3SinkConnector"
    "topics": "parking-entries,parking-exits"
    "format.class": "io.confluent.connect.s3.format.parquet.ParquetFormat"
    "flush.size": "100"
    "storage.class": "io.confluent.connect.s3.storage.S3Storage"
    "s3.bucket.name": "iceberg"
    "store.url": "http://rook-ceph-rgw-my-store.rook-ceph.svc:80"
    "topics.dir": "landing"
    "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner"
    "path.format": "'year'=YYYY/'month'=MM/'day'=dd"
    "partition.duration.ms": "86400000"
    "locale": "ko_KR"
    "timezone": "Asia/Seoul"
    "timestamp.extractor": "Record"

  # ★★★ 이 부분이 핵심입니다 ★★★
  # 위에서 정의한 s3-credentials-secret.yaml 파일을 참조합니다.
  secretRef:
    name: s3-credentials
