# spark-jobs/02-pipeline-schedule.yaml
# --- 작업 1: 데이터 품질 검증 (매시간 0분에 실행) ---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: parking-validation-schedule
  namespace: spark-operator
spec:
  schedule: "/10 * * * *"
  concurrencyPolicy: Forbid
  successfulRunHistoryLimit: 3
  failedRunHistoryLimit: 3
  template:
    type: Python
    mode: cluster
    image: "ich6648/spark-iceberg-nessie-kafka:9.0"
    imagePullPolicy: Always
    mainApplicationFile: "local:///mnt/scripts/data_validator.py"
    sparkVersion: "3.5.0"
    driver:
      serviceAccount: spark-sa
      cores: 1
      memory: "1g"
      envFrom:
        - secretRef:
            name: s3-creds-for-spark
      volumeMounts:
        - name: scripts-volume
          mountPath: /mnt/scripts
    executor:
      instances: 2
      cores: 1
      memory: "1g"
      envFrom:
        - secretRef:
            name: s3-creds-for-spark
      volumeMounts:
        - name: scripts-volume
          mountPath: /mnt/scripts
    volumes:
      - name: scripts-volume
        configMap:
          name: spark-scripts
---
# --- 작업 2: Main 브랜치 병합 (매시간 10분에 실행) ---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: parking-merge-to-main-schedule
  namespace: spark-operator
spec:
  schedule: "/30 * * * *"
  concurrencyPolicy: Forbid
  successfulRunHistoryLimit: 3
  failedRunHistoryLimit: 3
  template:
    type: Python
    mode: cluster
    image: "ich6648/spark-iceberg-nessie-kafka:9.0"
    mainApplicationFile: "local:///mnt/scripts/merge_to_main.py"
    sparkVersion: "3.5.0"
    driver:
      serviceAccount: spark-sa
      cores: 1
      memory: "512m"
      volumeMounts:
        - name: scripts-volume
          mountPath: /mnt/scripts
    executor:
      # [수정] Spark Operator 유효성 검사 규칙에 따라 instances는 1 이상이어야 합니다.
      instances: 1
      cores: 1
      memory: "512m"
      volumeMounts:
        - name: scripts-volume
          mountPath: /mnt/scripts
    volumes:
      - name: scripts-volume
        configMap:
          name: spark-scripts
