global:
  storageClass: "rook-ceph-block"

web:
  service:
    type: LoadBalancer
    ports:
      http: 8088

auth:
  # 사용자 이름과 비밀번호를 명시적으로 설정
  username: "admin"
  password: "admin"
  secretKey: 'p5gXv7yB9dE3fH2jL4mN6qR8tV0wZxC3bA1sF5uI7oK+Gg=='

postgresql:
  enabled: true
redis:
  enabled: true
