apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-my-store-external
  namespace: rook-ceph # RGW Pod이 있는 네임스페이스
spec:
  type: LoadBalancer
  selector:
    app: rook-ceph-rgw
    rgw: my-store # 대상 RGW 인스턴스를 정확히 지정
  ports:
    - name: http
      port: 8080 # 외부에서 접속할 포트
      targetPort: 80 # RGW Pod이 내부적으로 사용하는 포트
