apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-my-store-external
  namespace: rook-ceph
spec:
  type: LoadBalancer
  # Operator가 생성한 내부 서비스의 selector를 그대로 복사합니다.
  # 이렇게 하면 Pod을 정확하게 찾을 수 있습니다.
  selector:
    app: rook-ceph-rgw
    ceph_daemon_id: my-store
    rgw: my-store
    rook_cluster: rook-ceph
    rook_object_store: my-store
  ports:
    - name: http
      # 외부에서 접속할 포트 (LoadBalancer IP의 포트)는 그대로 80을 사용
      port: 80
      # ---▼ [수정] Pod이 실제로 요청을 기다리는 포트를 8080으로 변경합니다. ▼---
      targetPort: 8080
      # ---▲ [수정] 여기까지 수정합니다. ▲---
      protocol: TCP
