apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-my-store-external
  namespace: rook-ceph
spec:
  # --- [핵심 수정] ---
  # 타입을 LoadBalancer에서 NodePort로 변경합니다.
  type: NodePort
  # --------------------
  selector:
    # 이전에 확인했던 올바른 Selector를 그대로 사용합니다.
    app: rook-ceph-rgw
    ceph_daemon_id: my-store
    rgw: my-store
    rook_cluster: rook-ceph
    rook_object_store: my-store
  ports:
    - name: http
      # 외부에서 NodePort로 접속하면, 내부적으로는 80번 포트로 연결됩니다.
      port: 80
      targetPort: 80 # Pod이 실제로 요청을 기다리는 포트
      protocol: TCP
      # nodePort: 30581 # 특정 포트를 지정할 수도 있지만, 생략하면 쿠버네티스가 알아서 비어있는 포트를 할당합니다.
