apiVersion: v1
kind: Pod
metadata:
  name: s3-client
  # 이 Pod은 accumulation 네임스페이스에서 실행됩니다.
  namespace: accumulation
spec:
  containers:
  - name: mc
    image: minio/mc
    # Pod이 항상 실행 상태를 유지하도록 설정
    command: ["/bin/sh", "-c", "sleep infinity"]
    env:
      # --- 'accumulation' 네임스페이스의 Secret/ConfigMap에서 S3 접속 정보를 가져옵니다 ---
      - name: S3_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            # 'accumulation' 앱이 생성한 Secret 이름
            name: iceberg-bucket-claim
            key: AWS_ACCESS_KEY_ID
      - name: S3_SECRET_KEY
        valueFrom:
          secretKeyRef:
            # 'accumulation' 앱이 생성한 Secret 이름
            name: iceberg-bucket-claim
            key: AWS_SECRET_ACCESS_KEY
      - name: S3_HOST
        valueFrom:
          configMapKeyRef:
            # 'accumulation' 앱이 생성한 ConfigMap 이름
            name: iceberg-bucket-claim
            key: BUCKET_HOST
      - name: S3_PORT
        valueFrom:
          configMapKeyRef:
            # 'accumulation' 앱이 생성한 ConfigMap 이름
            name: iceberg-bucket-claim
            key: BUCKET_PORT
      - name: S3_BUCKET
        valueFrom:
          configMapKeyRef:
            # 'accumulation' 앱이 생성한 ConfigMap 이름
            name: iceberg-bucket-claim
            key: BUCKET_NAME
