apiVersion: apps/v1
kind: Deployment  # <-- kind를 Pod에서 Deployment로 변경
metadata:
  name: s3-client   # <-- Deployment의 이름
  namespace: accumulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-client # <-- 이 Deployment가 관리할 파드를 찾는 라벨
  template: # <-- 여기서부터가 실제 파드의 명세입니다 (Pod spec).
    metadata:
      labels:
        app: s3-client # <-- 파드에 붙일 라벨
    spec:
      containers:
      - name: mc
        image: minio/mc
        command: ["/bin/sh", "-c", "sleep infinity"]
        env:
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: iceberg-bucket-claim
                key: AWS_ACCESS_KEY_ID
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: iceberg-bucket-claim
                key: AWS_SECRET_ACCESS_KEY
          - name: S3_HOST
            valueFrom:
              configMapKeyRef:
                name: iceberg-bucket-claim
                key: BUCKET_HOST
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: iceberg-bucket-claim
                key: BUCKET_NAME
