# FILE: argocd/minix/apps/job-configs/01-rbac-secret.yaml
# 최종 수정: 올바른 S3 키와 완전한 RBAC 권한을 포함한 최종 버전

# --- 1. RBAC(역할 기반 접근 제어) 설정 ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: spark-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: spark-operator
rules:
  # Spark 드라이버가 자기 자신의 Pod 정보를 조회할 수 있는 권한
  - apiGroups: [""]
    resourceNames:
      - "${spark.driver.pod.name}"
    resources:
      - "pods"
    verbs:
      - "get"
  # Spark 드라이버가 자식(Executor) Pod와 Service 등을 관리할 일반 권한
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - deletecollection # 잡 종료 시 관련 리소스를 정리하기 위해 필수
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-binding
  namespace: spark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-driver-role
subjects:
  - kind: ServiceAccount
    name: spark-sa
    namespace: spark-operator
---
# --- 2. 스트리밍 잡을 위한 S3 접근 정보 Secret ---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds-for-streaming-spark
  namespace: spark-operator
type: Opaque
stringData:
  # 'iceberg-store'를 가리키는 내부 엔드포인트
  S3_ENDPOINT: "http://rook-ceph-rgw-iceberg-store.rook-ceph.svc:8080"
  # 'iceberg-bucket' OBC를 통해 발급받은 정확한 키 값
  S3_ACCESS_KEY: "0H6M0WR0NKACE547SCV9"
  S3_SECRET_KEY: "M9BqcrkVIEwIxNAmLWg3Rjt2xRbJdYmidkdjNZbQ"
