# FILE: argocd/minix/apps/job-configs/01-rbac-secret.yaml

# --- 1. RBAC(역할 기반 접근 제어) 설정 ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: spark-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: spark-operator
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-binding
  namespace: spark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-driver-role
subjects:
  - kind: ServiceAccount
    name: spark-sa
    namespace: spark-operator
---
# --- 2. 스트리밍 잡을 위한 S3 접근 정보 Secret ---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds-for-streaming-spark
  namespace: spark-operator
type: Opaque
stringData:
  # 'iceberg-store'를 가리키는 내부 엔드포인트
  S3_ENDPOINT: "http://rook-ceph-rgw-iceberg-store.rook-ceph.svc:8080"
  S3_ACCESS_KEY: "0H6M0WR0NKACE547SCV9chang" # iceberg-store의 Access Key
  S3_SECRET_KEY: "M9BqcrkVIEwIxNAmLWg3Rjt2xRbJdYmidkdjNZbQchang" # iceberg-store의 Secret Key
