---
apiVersion: v1
kind: Service
metadata:
  name: omniverse-nucleus
  namespace: omniverse
  labels:
    app.kubernetes.io/name: omniverse-nucleus
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: omniverse-nucleus
  ports:
    - name: web
      port: 8080
      targetPort: web
    - name: api-3009
      port: 3009
      targetPort: api-3009
    - name: api-3019
      port: 3019
      targetPort: api-3019
    - name: lft
      port: 3030
      targetPort: lft
    - name: auth-3100
      port: 3100
      targetPort: auth-3100
    - name: auth-3180
      port: 3180
      targetPort: auth-3180
    - name: discovery
      port: 3333
      targetPort: discovery
    - name: search
      port: 3400
      targetPort: search
