# ingestion/objectstore-claim.yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ingestion-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 1
  dataPool:
    failureDomain: osd
    replicated:
      size: 1
  gateway:
    type: s3
    replicas: 1
    port: 8080
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
  config:
    "rgw_frontends": "beast port=8080"
