apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  dataVolumeCapacity: 10Gi
  storageClass:
    name: rook-ceph-block-kafka
  image:
    application: confluentinc/cp-server:7.9.2
    init: confluentinc/confluent-init-container:2.11.2
  listeners:
    external:
      externalAccess:
        type: nodePort
        nodePort:
          host: 10.34.48.103               # 클러스터 노드 IP
          nodePortOffset: 31190            # → 31190, 31191, 31192
  podTemplate:
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "2Gi"
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  configOverrides:
    server:
      - "inter.broker.listener.name=INTERNAL"
      - "listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,REPLICATION:PLAINTEXT,CONTROLLER:PLAINTEXT"
      - "confluent.license.topic.replication.factor=3"
      - "confluent.metrics.reporter.topic.replication.factor=3"
      - "confluent.controlcenter.internal.topics.replication.factor=3"
      - "confluent.controlcenter.command.topic.replication.factor=3"
      - "confluent.monitoring.interceptor.topic.replication.factor=3"
