apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  dataVolumeCapacity: 10Gi
  storageClass:
    name: rook-ceph-block-kafka
  image:
    application: confluentinc/cp-server:7.9.2
    init: confluentinc/confluent-init-container:2.11.2
  listeners:
    external:
      externalAccess:
        type: loadBalancer # 'nodePort' 대신 'loadBalancer'를 사용
        loadBalancer:
          domain: minix.local
      tls:
        enabled: false
  podTemplate:
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "2Gi"
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  configOverrides:
    server:
      # [수정] 모든 리스너를 PLAINTEXT로 명시
      - "listener.security.protocol.map=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      - "inter.broker.listener.name=INTERNAL"

      # --- 클러스터 안정성 및 내부 토픽 설정 (유지) ---
      - "min.insync.replicas=2"
      - "confluent.license.topic.replication.factor=3"
      - "confluent.metrics.reporter.topic.replication.factor=3"
      - "confluent.controlcenter.internal.topics.replication.factor=3"
      - "confluent.controlcenter.command.topic.replication.factor=3"
      - "confluent.monitoring.interceptor.topic.replication.factor=3"
      - "confluent.schema.topic.replication.factor=3"
      - "default.replication.factor=3"
