# 02-kafka-cluster.yaml

apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  dataVolumeCapacity: 50Gi # 데이터 볼륨 용량은 그대로 유지
  storageClass:
    name: rook-ceph-block-kafka
  image:
    application: confluentinc/cp-server:7.9.2
    init: confluentinc/confluent-init-container:2.11.2
  listeners:
    internal:
      name: INTERNAL
      port: 9071
      type: internal
    external:
      name: EXTERNAL
      # ★★★ [최종 수정] 필수 항목인 host와 nodePortOffset 추가 ★★★
      externalAccess:
        type: nodePort
        nodePort:
          # [필수] kubectl get nodes -o wide 로 확인한 워커 노드 IP
          host: 10.34.48.100

          # [필수] 각 카프카 브로커에 할당될 NodePort의 시작 번호
          nodePortOffset: 32100
          
          # [선택] 최초 접속(bootstrap)을 위한 대표 포트
          bootstrapPort: 32092
  podTemplate:
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "2Gi"
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  configOverrides:
    server:
      # --- 기본 연결 및 복제 설정 ---
      - "inter.broker.listener.name=INTERNAL"
      - "listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,REPLICATION:PLAINTEXT"
      - "min.insync.replicas=2"
      - "default.replication.factor=3"
      
      # --- Confluent 내부 토픽 복제 설정 ---
      - "confluent.license.topic.replication.factor=3"
      - "confluent.controlcenter.internal.topics.replication.factor=3"
      - "confluent.controlcenter.command.topic.replication.factor=3"
      - "confluent.monitoring.interceptor.topic.replication.factor=3"
      - "confluent.schema.topic.replication.factor=3"

      # ★★★ 일반 토픽에 대한 '기본' 보존 정책 ★★★
      - "log.retention.hours=12"
      - "log.retention.bytes=536870912"
      - "log.segment.bytes=134217728"
      - "compression.type=lz4"

      # ★★★ 추가된 최적화: 내부 관리 토픽 보존 기간 단축 ★★★
      - "offsets.topic.retention.minutes=1440"
      - "transaction.state.log.retention.ms=86400000"
      
      # ★★★ 메트릭 토픽 최적화 (보존 정책 강화) ★★★
      - "confluent.metrics.reporter.enable=true"
      - "confluent.metrics.reporter.topic.partitions=3"
      - "confluent.metrics.reporter.topic.replication.factor=1"
      - "confluent.metrics.reporter.topic.retention.ms=1800000"
      - "confluent.metrics.reporter.topic.retention.bytes=1073741824"
      - "confluent.metrics.reporter.publish.ms=15000"
      
      # ★★★ 불필요한 기능 비활성화 (텔레메트리 설정 강화) ★★★
      - "confluent.telemetry.enable=false"
      - "confluent.reporters.telemetry.auto.enable=false"
      - "confluent.self.balancing.enable=false"
