# 파일: confluent-platform/02-kafka-cluster.yaml
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  dataVolumeCapacity: 10Gi
  storageClass:
    name: rook-ceph-block-kafka
  image:
    application: confluentinc/cp-server:7.9.2
    init: confluentinc/confluent-init-container:2.11.2
  listeners:
    # 클러스터 내부 통신용 (브로커 간, 다른 컴포넌트 간)
    internal:
      name: INTERNAL
      port: 9071
      type: internal
    # 클러스터 외부 통신용 (Omniverse, 외부 클라이언트용)
    external:
      name: EXTERNAL
      externalAccess:
        type: loadBalancer
        loadBalancer:
          # Operator가 'kafka-bootstrap-lb' 라는 이름의 대표 LoadBalancer를 생성하도록 함
          bootstrapService:
            name: kafka-bootstrap-lb
  podTemplate:
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "2Gi"
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  configOverrides:
    server:
      # 브로커들끼리 통신할 때는 'INTERNAL' 리스너를 사용하도록 지정
      - "inter.broker.listener.name=INTERNAL"
      # 보안 프로토콜 정의
      - "listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      # ★★★ 외부 접속을 위한 핵심 설정 ★★★
      - "advertised.listeners=INTERNAL://kafka-$(KAF-BROKER-ID).kafka.confluent.svc.cluster.local:9071,EXTERNAL://${CFK_EXTERNAL_LISTENER_HOST}:$(CFK_EXTERNAL_LISTENER_PORT)"
      # 데이터 안정성을 위한 설정
      - "min.insync.replicas=2"
      # Confluent 플랫폼 내부 토픽들의 복제본 수 설정
      - "confluent.license.topic.replication.factor=3"
      - "confluent.metrics.reporter.topic.replication.factor=3"
      - "confluent.controlcenter.internal.topics.replication.factor=3"
      - "confluent.controlcenter.command.topic.replication.factor=3"
      - "confluent.monitoring.interceptor.topic.replication.factor=3"
      - "confluent.schema.topic.replication.factor=3"
      - "default.replication.factor=3"
