apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  dataVolumeCapacity: 10Gi
  storageClass:
    name: rook-ceph-block-kafka
  image:
    application: confluentinc/cp-server:7.9.2
    init: confluentinc/confluent-init-container:2.11.2

  # --- [수정된 부분] ---
  # 기존 listeners 블록을 아래 내용으로 교체합니다.
  listeners:
    # 클러스터 내부 통신용 리스너 (필수)
    - name: internal
      port: 9071
      type: internal
      tls: false
      authentication:
        type: plain

    # 외부 접속을 위한 NodePort 리스너
    - name: external
      port: 9092
      type: nodeport
      tls: false
      authentication:
        type: plain
      # Kafka 브로커가 외부에 자신의 주소를 "광고(advertise)"할 때 사용할 설정
      config:
        # 외부에 알려줄 호스트(IP) 주소를 명시합니다.
        advertisedHost: 10.34.48.103
        # 브로커 0번이 사용할 NodePort를 31191로 지정합니다.
        # Confluent Operator가 자동으로 브로커 1번은 31192, 2번은 31193으로 설정합니다.
        nodePort:
          firstPort: 31191
  # --- [수정 끝] ---
  
  podTemplate:
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "2Gi"
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  configOverrides:
    server:
      - "inter.broker.listener.name=INTERNAL"
      - "listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,REPLICATION:PLAINTEXT,CONTROLLER:PLAINTEXT"
      - "confluent.license.topic.replication.factor=3"
      - "confluent.metrics.reporter.topic.replication.factor=3"
      - "confluent.controlcenter.internal.topics.replication.factor=3"
      - "confluent.controlcenter.command.topic.replication.factor=3"
      - "confluent.monitoring.interceptor.topic.replication.factor=3"
