apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  dataVolumeCapacity: 10Gi
  storageClass:
    name: rook-ceph-block-kafka
  listeners:
    external:
      name: external # 이 이름은 external 키와 일치해야 합니다.
      type: loadbalancer
      port: 9092
      authentication:
        type: plaintext
    # CFK는 내부 통신을 위한 internal 리스너를 자동으로 생성하지만,
    # 명시적으로 함께 정의해주는 것이 더 안전하고 명확합니다.
    internal:
      name: internal
      type: internal
      port: 9071
      authentication:
        type: plaintext
  image:
    application: confluentinc/cp-server:7.9.2
    init: confluentinc/confluent-init-container:2.11.2
  podTemplate:
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "2Gi"
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  configOverrides:
    server:
      - "confluent.license.topic.replication.factor=3"
      - "confluent.metrics.reporter.topic.replication.factor=3"
      - "confluent.controlcenter.internal.topics.replication.factor=3"
      - "confluent.controlcenter.command.topic.replication.factor=3"
      - "confluent.monitoring.interceptor.topic.replication.factor=3"
