apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 1
  dataVolumeCapacity: 2Gi
  storageClass:
    name: rook-ceph-block-kafka
  image:
    application: confluentinc/cp-ksqldb-server:8.0.0
    init: confluentinc/confluent-init-container:3.0.1
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
